import { Code } from "lucide-react";
import CodeMirror from "@uiw/react-codemirror";
import { javascript } from "@codemirror/lang-javascript";
import { dracula } from "@uiw/codemirror-themes";
import { useEffect, useState } from "react";

interface Question {
  problem: string;
  example: string;
  constraints: string;
  note: string;
}

const Canvas = () => {
  const [aiActive, setAiActive] = useState(false);
  const [question, setQuestion] = useState<Question | null>(null);
  const [feedback, setFeedback] = useState("");
  const [loading, setLoading] = useState(false);
  const [solved, setSolved] = useState(false);
  const [warning, setWarning] = useState("");
  const [difficulty, setDifficulty] = useState("");

  const initialCode = `function solution() {// Type your code here}`;
  const [code, setCode] = useState(initialCode);

  useEffect(() => {
    const checkReady = setInterval(() => {
      if (window.puter?.ai?.chat) {
        setAiActive(true);
        clearInterval(checkReady);
      }
    }, 300);

    return () => {
      clearInterval(checkReady);
    };
  }, []);

  const handleDifficulty = (level: string) => {
    setDifficulty(level);
    if (warning) setWarning("");
  };

  const generateQuestion = async () => {
    const coachLevels = ["Beginner", "Intermediate", "Expert"];

    if (!coachLevels.includes(difficulty)) {
      setWarning(
        "Please select a difficulty level before generating a question",
      );
      return;
    }

    if (!window.puter?.ai?.chat) {
      setWarning(
        "AI service is not available yet. Please try again in a moment.",
      );
      return;
    }

    setWarning("");
    setLoading(true);
    setFeedback("");
    setSolved(false);
    setCode(initialCode);
    setQuestion(null);

    try {
      const res = await window.puter.ai.chat(
        `
      Generate a random ${difficulty} level coding interview question like on LeetCode.
      Return ONLY valid JSON with this format:
      {
        "problem": "string",
        "example": "string",
        "constraints": "string",
        "note": "string or empty if none"
      }
      `,
      );

      const reply = typeof res === "string" ? res : res.message?.content || "";
      const parsed = JSON.parse(reply);
      setQuestion(parsed);
    } catch (err) {
      setFeedback(`Error: ${err instanceof Error ? err.message : String(err)}`);
    } finally {
      setLoading(false);
    }
  };

  const checkSolution = async () => {
    if (!code.trim()) return;

    setLoading(true);
    try {
      const res = await window.puter?.ai?.chat?.(
        `The question is: ${question?.problem}. Here is the candidates solution: \n ${code}. 
        1. If correct, say "Correct, well done".
        2. If wrong, give hints but don't reveal the answer"`,
      );

      const reply = typeof res === "string" ? res : res.message?.content || "";
      setFeedback(reply);
      if (reply.includes("Correct, well done")) setSolved(true);
    } catch (err) {
      setFeedback(`Error: ${err instanceof Error ? err.message : String(err)}`);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="w-full flex items-center justify-center">
      {!question ? 
      (<div className="w-full p-10 bg-gray-300 backdrop-blur-md rounded-lg border border-gray-500 text-center">
        <Code className="mx-auto mb-6 w-24 h-24"/>
        <h4 className="text-white font-semibold">Ready to Practice?</h4>
        <p className="text-slate-300 mb-8 text-lg leading-relaxed">Solve coding interview questions generated by AI, get hints,and improve your skills</p>
      </div>) 

      :
      
      (<div className="w-full">

      </div>)}
    </div>
  );
};

export default Canvas;
